services:
  gymbot_db:
    image: postgres:16
    container_name: gymbot_db
    hostname: gymbot_db
    restart: always
    ports:
      - '9981:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - core-infra

  gymbot_backend:
    image: "${BOT_IMAGE}:${BOT_TAG}"
    restart: always
    container_name: gymbot_backend
    hostname: gymbot_backend
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@gymbot_db:5432/${DB_NAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      WEB_APP_URL: ${WEB_APP_URL}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    ports:
      - "5400:5400"
    networks:
      - core-infra
    depends_on:
      - gymbot_db

  admin_backend:
    image: "${ADMIN_BACKEND_IMAGE}:${ADMIN_BACKEND_TAG}"
    restart: always
    container_name: admin_backend
    hostname: admin_backend
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: gymbot_db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
    ports:
      - "8001:8000"
    networks:
      - core-infra
    depends_on:
      - gymbot_db

  admin_frontend:
    image: "${ADMIN_FRONTEND_IMAGE}:${ADMIN_FRONTEND_TAG}"
    restart: always
    container_name: admin_frontend
    hostname: admin_frontend
    ports:
      - "5174:5173"
    networks:
      - core-infra
    depends_on:
      - admin_backend

networks:
  core-infra:
    external: true
